name: Luacheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v1.1.0
